---
# file: roles/database/tasks/main.yml
- name: MongoDB | Fetch 10Gen signing key
  command: apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10

- name: MongoDB | Add 10Gen repository
  shell:
    echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/10gen.list
    creates=/etc/apt/sources.list.d/10gen.list

- name: MongoDB | Install latest MongoDB release
  apt:
    pkg: mongodb-org=2.6.4
    state: present
    update_cache: yes
